### ISSUE TITLE
Improvement for API endpoints

### ISSUE THREAD

**Issue by fbagci** [smartictsolutions/active-directory-client#1]
Changing request types and endpoint names as shown below may be more appropriate in terms of best practices.

POST activedirectory/authentication    ->    POST activedirectory/authenticate
POST activedirectory/getAllUsers        ->    GET activedirectory/users

**Comment by smartictsolutions** [comment]
"POST activedirectory/getAllUsers -> GET activedirectory/users" it has to be POST request . You need to authenticate for getting users
